version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGODB_DATABASE="nest"
      - PUID=1000
      - PGID=1000
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 1.5
